name: dashboard
channels:
  - conda-forge
  - defaults
dependencies:
  - dash=1.14.0
  - dash-core-components=1.10.2
  - dash-html-components=1.0.3
  - flask=1.1.2
  - geopandas=0.8.1
  - matplotlib=3.3.1
  - pandas=1.1.2
  - plotly=4.10.0
  - python=3.8.5
  - rasterio=1.1.5
  - rasterstats=0.14.0
  - xlrd=1.2.0
